// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWSC2Hov_T2doS8EJxivnEB6d0waBaifQ',
    appId: '1:574964863834:web:c8b63e6a06e03b892b9963',
    messagingSenderId: '574964863834',
    projectId: 'phishingapp-92c43',
    authDomain: 'phishingapp-92c43.firebaseapp.com',
    storageBucket: 'phishingapp-92c43.appspot.com',
    measurementId: 'G-NFK9367Y39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xZgjlIo229J2RF8_bUZDmhvU9b3WVuw',
    appId: '1:574964863834:android:37102dec4234fb922b9963',
    messagingSenderId: '574964863834',
    projectId: 'phishingapp-92c43',
    storageBucket: 'phishingapp-92c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX15SoDVYj-R4JdfQOdvcXvu4qiK_cCeI',
    appId: '1:574964863834:ios:179651fb3d27545d2b9963',
    messagingSenderId: '574964863834',
    projectId: 'phishingapp-92c43',
    storageBucket: 'phishingapp-92c43.appspot.com',
    iosClientId: '574964863834-m793vfdrk7drg3vfv5dk49lrq9khbej4.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingSimulationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX15SoDVYj-R4JdfQOdvcXvu4qiK_cCeI',
    appId: '1:574964863834:ios:be2c5ead53d0f46c2b9963',
    messagingSenderId: '574964863834',
    projectId: 'phishingapp-92c43',
    storageBucket: 'phishingapp-92c43.appspot.com',
    iosClientId: '574964863834-c8it5cou2uu759g1tjqgrsgukrnu09ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingSimulationApp.RunnerTests',
  );
}
